### ISSUE TITLE
How run inference on a single wav file? 

### ISSUE THREAD

**Issue by paklau99988** [mobvoi/wenet#120]
No say here how to do:
https://github.com/mobvoi/wenet/blob/main/examples/aishell/s0/README.md

**Comment by robin1001** [comment]
Just follow the testing pipeline in run.sh to prepare your single test wave as required format for experiment.

For exported model for production, just follow https://github.com/mobvoi/wenet/tree/main/runtime/server/x86

**Comment by mikelei** [comment]
There is an offline ASR demo in https://github.com/mobvoi/wenet/tree/main/runtime/server/x86/README.md

**Comment by MisakaLee** [comment]
Actually, I follow the testing pipeline and found that the required format needs text and token even for tests. unbelievable.  Also, I try to use blank to replace the detail, but it does not work, it will just infer the item with all true information.

**Comment by pengzhendong** [comment]
@MisakaLee Do you mean decoder_main? You just input the wav path or the wav scp is OK.

**Comment by MisakaLee** [comment]
> @MisakaLee Do you mean decoder_main? You just input the wav path or the wav scp is OK.

The run.sh. I want to infer with python. 
But follow the shell, I have no idea to do that just input the .wav path. 
I try to write a format.data as follow:
warning/format.data
`utt:2775188979879799	feat:./Record/daily/20210201/2775188979879799.wav	feat_shape:92.94947845804988
utt:BAC009S0764W0121	feat:./data/data_aishell/wav/test/S0764/BAC009S0764W0121.wav	feat_shape:4.2039375    text: 	token: 	tokenid:
utt:BAC009S0764W0122	feat:./data/data_aishell/wav/test/S0764/BAC009S0764W0122.wav	feat_shape:4.115	text:一二线城市虽然也处于调整中	token:一 二 线 城 市 虽 然 也 处 于 调 整 中	tokenid:2 70 2885 764 1121 3308 2303 58 804 71 3502 1638 30	token_shape:13,4233
`
And change the path, but the it only test the third one and skip first two.
