### ISSUE TITLE
CMake error during server build

### ISSUE THREAD

**Issue by faranaziz** [mobvoi/wenet#126]
HEAD is now at 96a2f23 Merge pull request #419 from shinh/release-0-4-0
[ 33%] No patch step for 'glog-populate'
[ 44%] Performing update step for 'glog-populate'
[ 55%] No configure step for 'glog-populate'
[ 66%] No build step for 'glog-populate'
[ 77%] No install step for 'glog-populate'
[ 88%] No test step for 'glog-populate'
[100%] Completed 'glog-populate'
[100%] Built target glog-populate
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-targets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

**Comment by robin1001** [comment]
please make sure:
1. your cmake version is 3.14+.
2. glog is downloaded successfully. Sometimes cmake fails since package downloading fails

**Comment by faranaziz** [comment]
Have cmake 3.17, no work good yet.

**Comment by robin1001** [comment]
what about clean everything and make it again?

**Comment by faranaziz** [comment]
I did rm -rf build
Same result

**Comment by pengzhendong** [comment]
Could you please provide more details? Such as the total log or the platform.

**Comment by pengzhendong** [comment]
If clean everything not works. Please delete the repo and clone it again.

**Comment by apoca909** [comment]
rm -rf /usr/lib/x86_64-linux-gnu/cmake/gflags

cmake again 
it works

**Comment by FredSRichardson** [comment]
And can confirm that having a system gflags installed breaks the build.

**Comment by pengzhendong** [comment]
> And can confirm that having a system gflags installed breaks the build.

Fixed https://github.com/wenet-e2e/wenet/pull/1468. Now the pre-installed will not break the build.
