### ISSUE TITLE
android demo识别率很低

### ISSUE THREAD

**Issue by wchuan163** [mobvoi/wenet#147]
早上好你叫什么名字去机场要怎么走
识别成：
宝上方你这什欢名次却具残要车
准确率大概25%，是否因为lm没加的缘故

**Comment by robin1001** [comment]
it's just a demo, the prebuilt model only use 170 hours AIShell-1 data for training, it should be bad for most cases.
If you want better performance, just use more data to train your own model.

**Comment by wchuan163** [comment]
thank you the quick answer.
