### ISSUE TITLE
What are the possible reasons for this result？

### ISSUE THREAD

**Issue by sunchang272** [mobvoi/wenet#149]
![捕获](https://user-images.githubusercontent.com/50686847/107115900-a7bc7c80-6867-11eb-90d9-8e7c96c439b8.PNG)

pre-trained model : http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell/20210204_unified_transformer_exp.tar.gz
test data: ai-shell1

**Comment by robin1001** [comment]
@whiteshirt0429

**Comment by robin1001** [comment]
Have you changed the cmvn path in train.yaml

**Comment by sunchang272** [comment]
> Have you changed the cmvn path in train.yaml

Yes, or I can not get the result, it will prompt that the file cannot be found.
so I changed the _cmvn_file_ like that:
        cmvn_file:  ./20210204_unified_transformer_exp/global_cmvn
Is that right?

**Comment by robin1001** [comment]
![image](https://user-images.githubusercontent.com/6036624/107167467-ed0db500-69f3-11eb-8884-096b8580afa9.png)
I tried with this script, the result is reasonable.
