### ISSUE TITLE
Compile on Windows 10:   UnsatisfiedLinkError: couldn't find "libwenet.so"

### ISSUE THREAD

**Issue by xiao11lam** [mobvoi/wenet#150]
Hi, here is the problem, when I tried to compile the WENET latest android codes you offerred in my machine, and add the final.zip, words.txt file into the directory asked. However, it just crashed ( both the emulator in android studio and my perssonal cellphone) , always after I gave the permission for the privacy of recording.  I did some online search try to find out [[1]](https://github.com/facebook/fresco/issues/410) still, sadly all not work. Here are the problems which send back to me.  

And my environment is:   windows 10, sdk 6.0 - 9.0, Cmake 3.18.1.
![微信截图_20210206181812](https://user-images.githubusercontent.com/58770171/107116405-f42aab00-68ad-11eb-831b-9afbbc878ad7.png)

![微信截图_20210206182246](https://user-images.githubusercontent.com/58770171/107116412-0278c700-68ae-11eb-89da-cb1a609ec973.png)

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobvoi.wenet, PID: 11753
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mobvoi.wenet-VaKqTfUA4p7TCtqlZS2Gtg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mobvoi.wenet-VaKqTfUA4p7TCtqlZS2Gtg==/lib/arm, /data/app/com.mobvoi.wenet-VaKqTfUA4p7TCtqlZS2Gtg==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libwenet.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.mobvoi.wenet.Recognize.<clinit>(Recognize.java:6)
        at com.mobvoi.wenet.Recognize.init(Native Method)
        at com.mobvoi.wenet.MainActivity.onCreate(MainActivity.java:88)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by pengzhendong** [comment]
Have you change build.gradle? Please provide more details of your build.gradle file.

**Comment by jschenxiaoyu** [comment]
Hi xiao11lam, could you try `rm -rf app/build && rm -rf app/.cxx && ./gradlew cleanBuildCache && ./gradlew build`

**Comment by xiao11lam** [comment]
> Have you modified build.gradle? Please provide more details of your build.gradle file.

Here is my build.gradle file, please kindly refer to it.

```
plugins {
    id 'com.android.application'
}

repositories {
    jcenter()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

android {
    signingConfigs {
        release {
            storeFile file('wenet.keystore')
            storePassword '123456'
            keyAlias 'wenet'
            keyPassword '123456'
        }
    }
    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
    configurations {
        extractForNativeBuild
    }
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.mobvoi.wenet"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                targets  "wenet", "decoder_main"
                cppFlags "-std=c++14", "-DC10_USE_GLOG", "-DC10_USE_MINIMAL_GLOG", "-DANDROID", "-Wno-c++11-narrowing", "-fexceptions"
            }
        }

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'org.pytorch:pytorch_android:1.6.0'
    extractForNativeBuild 'org.pytorch:pytorch_android:1.6.0'
}

task extractAARForNativeBuild {
    doLast {
        configurations.extractForNativeBuild.files.each {
            def file = it.absoluteFile
            copy {
                from zipTree(file)
                into "$buildDir/$file.name"
                include "headers/**"
                include "jni/**"
            }
        }
    }
}

tasks.whenTaskAdded { task ->
    if (task.name.contains('externalNativeBuild')) {
        task.dependsOn(extractAARForNativeBuild)
    }
}
```

**Comment by xiao11lam** [comment]
> Hi xiao11lam, could you try `rm -rf app/build && rm -rf app/.cxx && ./gradlew cleanBuildCache && ./gradlew build` and show us the detailed log?

Hi, I am not very familiar with this shell and my machine is ran on windows , since I mostly relayed on IDE. Could you explain another way for me to report the issue?

**Comment by xiao11lam** [comment]
Thank you for @pengzhendong and his patient instructions.

Here it is:

First of all, due to my OS is windows 10. Although we strongly suggest that you test on a linux/mac machine, but here is the problem you may face with if you insist running on a PC. 

The main problem here is : _"**The Wenet is not built**"_ or some other problems related with this issue.

In this case,  we just need to go to the path: `$runtime/device/android/wenet$` in our cmd and then input command:

`.\gradlew build`

![微信截图_20210207225249](https://user-images.githubusercontent.com/58770171/107150692-11d53e80-699a-11eb-994c-c01a63c79cd0.png)

After everything is fixed, you will get a **Build Success** notification like this:

![微信截图_20210207225320](https://user-images.githubusercontent.com/58770171/107150703-20bbf100-699a-11eb-8a8c-a2772312ea45.png)

Finally, we may compile our android APP successfully on our Android Studio:

By the way, if you want to use your virtual emulator to do the testing, you should as well manipulate the part where the red arrow points to, just add `"x86", "x86_64"` into the gradle file. 

![微信截图_20210207230028](https://user-images.githubusercontent.com/58770171/107150771-81e3c480-699a-11eb-8a5b-3c29db87b411.png)

**Comment by jschenxiaoyu** [comment]
Thank you for your feedback and we will add "x86", "x86_64" into the gradle file in the next version
