### ISSUE TITLE
Indiscriminate sed replacement triggers `use_static_chunk` issue

### ISSUE THREAD

**Issue by AdolfVonKleist** [mobvoi/wenet#165]
The following `sed` command in the librispeech s0 recipe switches all instances of `dynamic` to `static`, which if a `train_unified_conformer.yml` recipe is used causes the `use_dynamic_chunk: true` to be replaced with `use_static_chunk: true` at eval time.  

> TypeError: __init__() got an unexpected keyword argument 'use_static_chunk'

* https://github.com/mobvoi/wenet/blob/a1250553371097826da13fb1a9438a9e8a9dc110/examples/librispeech/s0/run.sh#L183

this is easily fixed by modifying the above `run.sh` line.  But I wonder if there is something else going on there that I missed that could still affect the accuracy of the model at training/decode time. It seems to work OK, but I don't find this in the aishell `run.sh` for either recipe.

**Comment by whiteshirt0429** [comment]
sorry, we have just take a spring festival vocation, it was a  bug, and I will remove it

**Comment by whiteshirt0429** [comment]
sorry for our slow reply, it was indeed a bug, and I will remove it
