### ISSUE TITLE
Can we output time duration for each word？





### ISSUE THREAD

**Issue by Mddct** [mobvoi/wenet#167]

**Comment by robin1001** [comment]
Yes, it's ongoing now, and it will be ready soon. I will notice you once it is ready.

**Comment by Mddct** [comment]
Time duration  from attention weight or ctc output ？

**Comment by ansong1024** [comment]
ctc output

**Comment by Mddct** [comment]
awesome

**Comment by proger** [comment]
Found some code here https://github.com/wenet-e2e/wenet/pull/250/files#diff-9fd05896a110daa02dfe6ad95a33c00839a59adc697df1a804c7aa9d4937b0d5R156-R174
