### ISSUE TITLE
How many milliseconds of delay does different chunk correspond to?

### ISSUE THREAD

**Issue by TeaPoly** [mobvoi/wenet#17]
I notice chunk 1 degradation 30% (from 5.51 to 7.83) in section "Unified Dynamic chunk"  ctc greedy search. 

Please let me know if my understanding is incorrect:
Chunk 1 delay conversion is 12layers\*1chunk\*40ms(conv2d) = 480 ms.

**Comment by robin1001** [comment]
The latency is only related to chunk size and sampling rate(conv2d, 40ms),  so for chunk 1, the delay is 1 * 40=40ms, and for chunk 16, the delay is 16 * 40 = 640ms.

We are preparing the paper, I will provide the paper link in a few days once it is ready.

**Comment by robin1001** [comment]
The latency is only related to chunk size and sampling rate(conv2d, 40ms),  so for chunk 1, the delay is 1 * 40=40ms, and for chunk 16, the delay is 16 * 40 = 640ms.

We are preparing the paper, I will provide the paper link in a few days once it is ready.

**Comment by TeaPoly** [comment]
Thanks for your reply.

**Comment by robin1001** [comment]
> I notice chunk 1 degradation 30% (from 5.51 to 7.83) in section "Unified Dynamic chunk" ctc greedy search.
> 
> Please let me know if my understanding is incorrect:
> Chunk 1 delay conversion is 12layers*1chunk*40ms(conv2d) = 480 ms.

Hi TeaPloy, please see more details at https://arxiv.org/abs/2012.05481, the paper is the first draft, we are still refining it. Hope it helps.

**Comment by TeaPoly** [comment]
> > I notice chunk 1 degradation 30% (from 5.51 to 7.83) in section "Unified Dynamic chunk" ctc greedy search.
> > Please let me know if my understanding is incorrect:
> > Chunk 1 delay conversion is 12layers_1chunk_40ms(conv2d) = 480 ms.
> 
> Hi TeaPloy, please see more details at https://arxiv.org/abs/2012.05481, the paper is the first draft, we are still refining it. Hope it helps.

Thanks.

**Comment by TeaPoly** [comment]
> The latency is only related to chunk size and sampling rate(conv2d, 40ms), so for chunk 1, the delay is 1 * 40=40ms, and for chunk 16, the delay is 16 * 40 = 640ms.
> 
> We are preparing the paper, I will provide the paper link in a few days once it is ready.

Bother you again, whether the history context is infinite?

<img width="314" alt="截屏2020-12-11 下午7 06 10" src="https://user-images.githubusercontent.com/3815778/101896411-f04b1700-3be3-11eb-8886-03805ac4e49b.png">

**Comment by robin1001** [comment]
> > The latency is only related to chunk size and sampling rate(conv2d, 40ms), so for chunk 1, the delay is 1 * 40=40ms, and for chunk 16, the delay is 16 * 40 = 640ms.
> > We are preparing the paper, I will provide the paper link in a few days once it is ready.
> 
> Bother you again, whether the history context is infinite?
> 
> <img alt="截屏2020-12-11 下午7 06 10" width="314" src="https://user-images.githubusercontent.com/3815778/101896411-f04b1700-3be3-11eb-8886-03805ac4e49b.png">

Yes，history context is the whole history.
