### ISSUE TITLE
无法使用多卡运行

### ISSUE THREAD

**Issue by boji123** [mobvoi/wenet#184]
我clone了wenet的最新版本，然后想使用双卡来跑aishell1的demo，但是运行后报如下错误：
单卡是没有问题的，似乎是缺少一个flock的函数？

Traceback (most recent call last):
Traceback (most recent call last):
  File "wenet/bin/train.py", line 185, in <module>
  File "wenet/bin/train.py", line 185, in <module>
    model = torch.nn.parallel.DistributedDataParallel(
  File "/dev/conda_py38/envs/wenet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 331, in __init__
    model = torch.nn.parallel.DistributedDataParallel(
  File "/dev/conda_py38/envs/wenet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 331, in __init__
    self._distributed_broadcast_coalesced(
  File "/dev/conda_py38/envs/wenet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "/dev/conda_py38/envs/wenet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: flock: Function not implemented
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: flock: Function not implemented
terminate called after throwing an instance of 'std::system_error'
  what():  flock: Function not implemented
terminate called after throwing an instance of 'std::system_error'
  what():  flock: Function not implemented

**Comment by robin1001** [comment]
Please
1. check your pytorch and cuda version
2. try to run it on a new machine to see whether it works.

**Comment by boji123** [comment]
I have followed the installation instructions line by line and change a new machine seems useless

**Comment by robin1001** [comment]
Maybe you can join our WeChat group and figure out if anybody has the same problem and the solution.

**Comment by boji123** [comment]
solved. the `init_method=file://$(readlink -f $INIT_FILE) ` seems call a global path and cause some version conflict problem
just simply call `dist.init_process_group(args.dist_backend)`

**Comment by robin1001** [comment]
Great, and can you describe the  version conflict problem in detail?

**Comment by placebokkk** [comment]
@boji123 Thank you! If this is a bug, could you help submit a PR?

**Comment by 11721206** [comment]
> solved. the `init_method=file://$(readlink -f $INIT_FILE) ` seems call a global path and cause some version conflict problem just simply call `dist.init_process_group(args.dist_backend)`

how solved the problem without changing the version? Thanks. I changed train.py          dist.init_process_group(args.dist_backend, init_method=args.init_method,   world_size=args.world_size,    rank=args.rank)
into 
dist.init_process_group(args.dist_backend);
the error still occurs.
