### ISSUE TITLE
Alphabet based training

### ISSUE THREAD

**Issue by pKrysenko** [mobvoi/wenet#185]
Is there any possibility to train model based on alphabet, not token?

**Comment by robin1001** [comment]
token means word piece? alphabet means character?

**Comment by pKrysenko** [comment]
Yes, you understand correct

**Comment by robin1001** [comment]
character can be used as model unit, just change the pipeline to use char. Generally, char has lower accuracy than word piece, so word piece is used as default model unit.

**Comment by pKrysenko** [comment]
With low resource data character based model shows better results then word piece model, based on my small research.
As far as i understand, only i need to change is the format.data file for training. if i use characters to train, i have to change, for instance, "▁CHAPTER ▁ONE" to "CHAPTER<space>ONE" and corresponding token ids and i don't need to decode text_bpe in test stage, am i right?

**Comment by robin1001** [comment]
for "CHAPTER ONE", the format.data should be "C H A P T E R <space> O N E", and the dict should be A-Z plus <space>.

**Comment by robin1001** [comment]
> for "CHAPTER ONE", the format.data should be "C H A P T E R [space] O N E", and the dict should be A-Z plus [space].

where [space] could be also replaced with a special char "▁" to simplify data processing.

**Comment by pKrysenko** [comment]
For dict is:
<blank> 0
<unk> 1
A 2
...
Z 28
<sos/eos> 29
Am i right?

**Comment by robin1001** [comment]
add one special symbol for space.

**Comment by pKrysenko** [comment]
Okey, many thanks and that's all what i need to change?

**Comment by robin1001** [comment]
1. the dict
2. training corpus should be prepared as char, such as "CHAPTER ONE", the format.data should be "C H A P T E R [space] O N E"

**Comment by pKrysenko** [comment]
Many thanks, sorry for dumb questions !
