### ISSUE TITLE
An error occurred while running on Android

### ISSUE THREAD

**Issue by TalentJack** [mobvoi/wenet#195]
I downloaded final.zip and words.txt, put them into Assets folder, and compiled the project into APK to run on Android system. When I open the app and click the button, it will report an error and flash back.

The error message is as followed :

26715-27453/com.mobvoi.wenet E/libc++abi: terminating with uncaught exception of type c10::Error: Expected at most 5 argument(s) for operator 'forward_encoder_chunk', but received 7 argument(s). Declaration: forward_encoder_chunk(__torch__.wenet.transformer.asr_model.___torch_mangle_21.ASRModel self, Tensor xs, Tensor? subsampling_cache=None, Tensor[]? elayers_output_cache=None, Tensor[]? conformer_cnn_cache=None) -> ((Tensor, Tensor, Tensor[], Tensor[]))
    Exception raised from checkAndNormalizeInputs at ../aten/src/ATen/core/function_schema_inl.h:245 (most recent call first):
    (no backtrace available)

26715-27453/com.mobvoi.wenet A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27453 (om.mobvoi.wenet), pid 26715 (om.mobvoi.wenet)

**Comment by robin1001** [comment]
@pengzhendong

**Comment by pengzhendong** [comment]
@TalentJack We have updated the model. So, please download it again.

**Comment by TalentJack** [comment]
Thanks for your reply. I tried the new model, but the error still exists. 

The error log is as follows:

11964-12009/com.mobvoi.wenet A/libc: /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type c10::Error: Expected at most 5 argument(s) for operator 'forward_encoder_chunk', but received 7 argument(s). Declaration: forward_encoder_chunk(__torch__.wenet.transformer.asr_model.___torch_mangle_21.ASRModel self, Tensor xs, Tensor? subsampling_cache=None, Tensor[]? elayers_output_cache=None, Tensor[]? conformer_cnn_cache=None) -> ((Tensor, Tensor, Tensor[], Tensor[]))
    Exception raised from checkAndNormalizeInputs at ../aten/src/ATen/core/function_schema_inl.h:245 (most recent call first):
    (no backtrace available)" failed

11964-12009/com.mobvoi.wenet A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12009 (om.mobvoi.wenet), pid 11964 (om.mobvoi.wenet)

**Comment by pengzhendong** [comment]
@TalentJack Is the model named 20210221_unified_transformer_device.tar.gz?

**Comment by TalentJack** [comment]
Yes, I'm sure I downloaded the new model named 20210221_unified_transformer_device.tar.gz

**Comment by pengzhendong** [comment]
@TalentJack Please delete the `.cxx` folder and the `build` folder, then try it again.

**Comment by TalentJack** [comment]
I've tried. but the problem is the same.

**Comment by pengzhendong** [comment]
哥们，能加个微信聊聊吗：wx275331498

**Comment by TalentJack** [comment]
感谢震东大哥加微信耐心帮忙解决问题，还远程帮忙调试，最终发现问题出在虚拟机上，用手机运行就没问题了。
希望wenet越来越好，星数早日超越espnet！

Thank @pengzhendong  for his patience to help solve the problem and help debugging remotely. Finally, we found that the problem was on the virtual machine, and we can run it successfully with the mobile phone.
Hope WENET gets better and better, and surpass ESPNET in star count!
