### ISSUE TITLE
Stage 3 shows no such file or directory

### ISSUE THREAD

**Issue by DaweiXi360** [mobvoi/wenet#200]
I followed the instruct line by line, and when bash run.sh --stage 3 --stop-stage 3, it showed no such file or directory, what can I do? Thanks.

**Describe the bug**
tools/format_data.sh --nj 32 --feat-type wav --feat raw_wav/dev/wav.scp raw_wav/dev data/dict/lang_char.txt
split: illegal option -- -
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
ls: raw_wav/dev/log/wav_*.slice: No such file or directory
cat: raw_wav/dev/log/wav_*.shape: No such file or directory
tools/format_data.sh --nj 32 --feat-type wav --feat raw_wav/test/wav.scp raw_wav/test data/dict/lang_char.txt
split: illegal option -- -
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
ls: raw_wav/test/log/wav_*.slice: No such file or directory
cat: raw_wav/test/log/wav_*.shape: No such file or directory
tools/format_data.sh --nj 32 --feat-type wav --feat raw_wav/train/wav.scp raw_wav/train data/dict/lang_char.txt
split: illegal option -- -
usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
             [file [prefix]]
ls: raw_wav/train/log/wav_*.slice: No such file or directory
cat: raw_wav/train/log/wav_*.shape: No such file or directory

**Desktop (please complete the following information):**
 - OS: Mac os

**Comment by robin1001** [comment]
The whole training pipeline is only tested on Linux, please try it on Linux. some shell commands have different arguments and behavior for Max and Linux.

**Comment by DaweiXi360** [comment]
got it
