### ISSUE TITLE
Forward chunk by chunk in decoding mode 

### ISSUE THREAD

**Issue by KarosChen** [mobvoi/wenet#205]
I can't understand forward chunk by chunk function in encoder.py

So, I have some problem about process of calculating right context parameter and 
how to use it in forward chunk by chunk problem

1. How to calculate context parameter like self.right context included in Conv2dSubsampling4 class in subsampling.py ?
2. What is the frame_rate_of_this_layer in Conv2dSubsampling4 ?
3. Why feed forward overlap input step by step in forward_chunk_by_chunk ?
4. What is the stride and decoding_window and how to calculate them in forward_chunk_by_chunk?

Can anyone solve my problem ?

**Comment by robin1001** [comment]
forward_chunk_by_chunk is just designed to simulate the streaming decoding fashion. 
Please see the document here, https://mobvoi.github.io/wenet/runtime.html,  I think it can solve all the problems you listed above.
