### ISSUE TITLE
你们会放出multi-cn的conformer的pretrain model吗

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [mobvoi/wenet#219]
感谢分享这么棒的工作
想问一下 你们会分享multi-cn的conformer的pretrain model吗

**Comment by chwma0** [comment]
找开源数据训就好啦啊，我都快训完了

**Comment by jike-algorithm-zhangxiao** [comment]
> 找开源数据训就好啦啊，我都快训完了

multi-cn 里面有用anishell2的数据, 这个没开源呀

**Comment by robin1001** [comment]
过两三周就会开放

**Comment by jike-algorithm-zhangxiao** [comment]
好的 期待

**Comment by bigcash** [comment]
请问multi-cn的conformer的pretrain model开源了吗，我没有找到呢
