### ISSUE TITLE
wav file parsing error when using runtime/server/x86/build/decoder_main

### ISSUE THREAD

**Issue by Emntee** [mobvoi/wenet#220]
when I pass some wav files to `decoder_main` I may encounter exceptions as follows:
```
I0317 14:59:13.375226  1310 torch_asr_model.cc:36] torch model info subsampling_rate 4 right context 6 sos 4232 eos 4232
I0317 14:59:13.379293  1310 decoder_main.cc:80] num frames 0
I0317 14:59:13.379323  1310 torch_asr_decoder.cc:77] Required 2147483647 get 0
terminate called after throwing an instance of 'c10::Error'
  what():  There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, QuantizedCPU, Autograd, Profiler, Tracer, Autocast]
```
I guess it's a error caused by frontend/wav.h, in wav.h
```
# wav.h 
...
# line 31
struct WavHeader {
  char riff[4];  // "riff"
  unsigned int size;
  char wav[4];  // "WAVE"
  char fmt[4];  // "fmt "
  unsigned int fmt_size;
  uint16_t format;
  uint16_t channels;
  unsigned int sample_rate;
  unsigned int bytes_per_second;
  uint16_t block_size;
  uint16_t bit;
  char data[4];  // "data"
  unsigned int data_size;
};
...
# line 56
fread(&header, 1, sizeof(header), fp);
...
# line 72
    int num_data = header.data_size / (bits_per_sample_ / 8);
    data_ = new float[num_data];
    num_sample_ = num_data / num_channel_;
```
There is a struct containing RIFF-FORMAT-DATA chunk, while sometimes, a fine wav file may contain some other chunks in wav header, like fact chunk and list chunk , when we process audio files with ffmpeg or pydub which is based on ffmpeg, there's a high possibility a LIST CHUNK encoded into generated wav file, you can talk this [link](https://stackoverflow.com/questions/39668146/ffmpeg-making-a-clean-wav-file) as a reference. 

A better way I guess is to read 4 bytes detecting which chunk the following part is, and then process it, after the data chunk is detected, then we can continue with next steps. 

I'm not familiar with C/C++ coding, and not sure if my analysis is correct, but if it is, hope you can fix it or add a notification in README, it will be of great help, thanks :-)

**Comment by robin1001** [comment]
Yes, it's right. Currently, only strict wav format is supported. It's not a urgent now, you can try to convert it by sox to get a strict wav format.
