### ISSUE TITLE
wrong cmvn_opt path in multi_cn run.sh

### ISSUE THREAD

**Issue by kli017** [mobvoi/wenet#224]
When I run stage 4 of multi_cn run.sh
It gives an error: raw_wav/train/global_cmvn': No such file or directory

In the run.sh line 225, I think the path should be **$cmvn && cp ${feat_dir}}_${en_modeling_unit}/${train_set}/global_cmvn $dir** ?
![image](https://user-images.githubusercontent.com/14877573/111740668-1a396700-88c0-11eb-8b9a-2443f54d60fc.png)

**Comment by whiteshirt0429** [comment]
it was a path bug, i have commit a new pr : https://github.com/mobvoi/wenet/pull/225
