### ISSUE TITLE
x86 RuntimeError

### ISSUE THREAD

**Issue by lfgogogo** [mobvoi/wenet#228]
非常感谢wenet的开源工作(๑•̀ㅂ•́)و✧！
以下是完整的报错：
![impicture_20210323_142254](https://user-images.githubusercontent.com/42054022/112102493-4f58f880-8be3-11eb-8180-bcd5b8742d83.jpg)
![impicture_20210323_142301](https://user-images.githubusercontent.com/42054022/112102498-52ec7f80-8be3-11eb-9f16-2f6b75569c85.jpg)

这里跑x86用的模型是自己用8k音频训练的模型，然后把c++源码里的16k全部改成了8k，编译完成测试的时候报了上面的错，哪位知道解决办法还望赐教。

**Comment by robin1001** [comment]
what's your version, please update your code to the latest, and re export your model. It should work.

**Comment by lfgogogo** [comment]
I update the code,it works ,great!
