### ISSUE TITLE
tools/format_data.sh bug

### ISSUE THREAD

**Issue by whispercosat** [mobvoi/wenet#236]
tools/format_data.sh文件89行
"${trans_type}" == "ch_char_en_bpe"  是否应该写作 "${trans_type}" == "cn_char_en_bpe"

**Comment by robin1001** [comment]
Good catch. Can you make a PR?

**Comment by whispercosat** [comment]
> Good catch. Can you make a PR?

已提交 谢谢彬彬哥

**Comment by robin1001** [comment]
厉害了，我的哥
