### ISSUE TITLE
doubts about x86 results

### ISSUE THREAD

**Issue by lfgogogo** [mobvoi/wenet#252]
1、In the x86 results,it seems the rescored results are not sent to the client,since i can only see partial results printed on the client side.
2、When i use > to redirect results so that i can compute CER later,on the client side,the log file has no problem,but on the server side,the log file is unreadable

I read the code but don't know how to send the final result to the client side,server side log file is unreadable,so i can't compute the CER,too.

**Comment by lfgogogo** [comment]
And it seems the final result always misses one character .Anyone tell me how to solve these questions? Hope for answer.

**Comment by pengzhendong** [comment]
https://github.com/mobvoi/wenet/blob/4beb5efd68b1da4f444e5e66e7e25383b4322937/runtime/core/websocket/websocket_server.cc#L82

> And it seems the final result always misses one character.

We have fixed the bug. BTW, why not calculate the WER using decoder_main.

**Comment by lfgogogo** [comment]
@pengzhendong I think the online mode is diffirent,it cuts the wavs and recognizes them,so the CER may be higher.Isn't decoder_main recognizing the whole wav once?

**Comment by lfgogogo** [comment]
@pengzhendong I think the online mode is diffirent,it cuts the wavs and recognizes them,so the CER may be higher.Isn't decoder_main recognizing the whole wav once?
