### ISSUE TITLE
After training some epochs, got "CUDA out of memory" error

### ISSUE THREAD

**Issue by JackHenry1992** [mobvoi/wenet#260]
After training some epochs, it runs into `the CUDA out of memory` error.
![image](https://user-images.githubusercontent.com/9390228/112948369-93f80d00-916a-11eb-945e-e2173bd86184.png)

I have trained 5 epochs successfully.
![image](https://user-images.githubusercontent.com/9390228/112948917-36b08b80-916b-11eb-801c-60e124f3afe4.png)

**Comment by ansong1024** [comment]
You need to reduce the batchsize

**Comment by SWHL** [comment]
- I have met the same problem.
- I think it is not the problem of batch size.  
- Because the first 5 epochs can be successfully trained, which means  it is not a problem of batch size. 
- It may be should be caused by a leak of memory.
