### ISSUE TITLE
使用docker环境编译运行server最新代码出错;failed to run new code in docker environment

### ISSUE THREAD

**Issue by paopjian** [mobvoi/wenet#281]
**Describe the bug**
clone the latest code from the github and cmake the code. When running the server, it throws errors

**To Reproduce**
1. docker run --rm -it mobvoiwenet/wenet:v0.1.0 bash
2. git clone https://github.com/mobvoi/wenet.git
3. mkdir build && cd build && cmake .. && cmake --build .
4. run the server 
export GLOG_logtostderr=1
export GLOG_v=2
model_dir=your_model_dir
./build/websocket_server_main \
    --port 10086 \
    --chunk_size 16 \
    --model_path $model_dir/final.zip \
    --dict_path $model_dir/words.txt 2>&1 | tee server.log

**Screenshots**
![image](https://user-images.githubusercontent.com/20377352/113805848-2b57f400-9759-11eb-827a-8b7b68e15ca0.png)

**Comment by whiteshirt0429** [comment]
perhaps you should re-export your old model by using the new version code
