### ISSUE TITLE
使用web前端快速开启关闭语音识别导致服务端死循环

### ISSUE THREAD

**Issue by paopjian** [mobvoi/wenet#286]
**Describe the bug**
点击网页的开始识别不说话并快速点击结束识别,会导致服务端程序死循环

**To Reproduce**
1. 启动server
2. 打开web前端
3. 点击开始识别,迅速点击结束时别
4. server崩溃死循环

**Screenshots**
server:
![image](https://user-images.githubusercontent.com/20377352/113830419-80f2c780-977e-11eb-8ce4-4b124b08c217.png)
web前端
![image](https://user-images.githubusercontent.com/20377352/113830892-f494d480-977e-11eb-8434-c66b3824e39c.png)

**Desktop (please complete the following information):**
 - OS: docker, ubuntu 20:04
 - Browser chrome
 - Version Docker version 20.10.5

可能是前端代码问题

**Comment by pengzhendong** [comment]
这个问题应该已经修复了 #290
