### ISSUE TITLE
Runtime model for Librispeech

### ISSUE THREAD

**Issue by singhaki** [mobvoi/wenet#294]
Hi, 

Thanks for this project. I have some questions in my mind.

1. How can we export the librispeech-unified model for runtime. I have already tried exporting it but in runtime, it is not giving any output.
2. Can we use Wav2vec-XLSR model for finetuning the encoder? we can use the hugging face transformers project for this.
3. when can we expect lm support?

**Comment by robin1001** [comment]
1. it should be easy to export the model, just follow run.sh to export your model.
2. There is no plan for this in the near future.
3. LM is ongoing. Maybe it will be ready in a few weeks.

**Comment by singhaki** [comment]
@robin1001 Thanks for reply. yaa the model was exported successfully. there was a problem in my wav file that is why it was giving a blank response. It works fine in web app.
