### ISSUE TITLE
result of the streaming recog is much worser than result of the wenet/bin/recognize.py

### ISSUE THREAD

**Issue by lfgogogo** [mobvoi/wenet#320]
I use the x86 and wenet/bin/recognize.py to test the same dataset,cer of streaming recog is 0.23 while cer of recognize.py is 0.15.
I check the models are same,the parameters are same,but the results have big gap.
By the way,the model is trained using aishell/s0,8k audioes.
Hope for suggestions to solve this,maybe i do something wrong,please fingure it out,3q.

**Comment by robin1001** [comment]
0.23 means 23% or 0.23%?
The frontend in c++ runtime is slightly different to python. so slight WER difference is reasonable.

**Comment by lfgogogo** [comment]
Cer of streaming recog is 23% while cer of recognize.py is 15%,maybe this isn't slightly different.

**Comment by lfgogogo** [comment]
Cer of streaming recog is 23% while cer of recognize.py is 15%,maybe this isn't slightly different.

**Comment by pengzhendong** [comment]
fixed. #348
