### ISSUE TITLE
step4 run error ， the error log as follow，which files should be  modify to correct it ? thanks

### ISSUE THREAD

**Issue by l2009312042** [mobvoi/wenet#33]
root@e62b3865c7cc:~/data/project/wenet/examples/aishell/s0# ./run.sh 
./run.sh: init method is file:///root/data/project/wenet/examples/aishell/s0/exp/sp_spec_aug/ddp_init
wenet/bin/train.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(fin)
Traceback (most recent call last):
  File "wenet/bin/train.py", line 82, in <module>
    **configs['spec_aug_conf'],
KeyError: 'spec_aug_conf'
wenet/bin/train.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(fin)
Traceback (most recent call last):
  File "wenet/bin/train.py", line 82, in <module>
    **configs['spec_aug_conf'],
KeyError: 'spec_aug_conf'
do model average and final checkpoint is exp/sp_spec_aug/avg_10.pt
Namespace(dst_model='exp/sp_spec_aug/avg_10.pt', max_epoch=65536, min_epoch=0, num=10, src_path='exp/sp_spec_aug', val_best=True)
Traceback (most recent call last):
  File "wenet/bin/average_model.py", line 47, in <module>
    sort_idx = np.argsort(val_scores[:, -1])
IndexError: too many indices for array
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 81, in <module>
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/train.yaml'
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 81, in <module>
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/train.yaml'
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 81, in <module>
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/train.yaml'
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 81, in <module>
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/train.yaml'
./run.sh: line 165: python2: command not found
./run.sh: line 165: python2: command not found
./run.sh: line 165: python2: command not found
./run.sh: line 165: python2: command not found
Traceback (most recent call last):
  File "wenet/bin/export_jit.py", line 29, in <module>
    with open(args.config, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/sp_spec_aug/train.yaml'

**Comment by whiteshirt0429** [comment]
sorry, it is a bug, i will fix it right now, and you can also use add spec_aug confing like one in librispeech recipe

**Comment by l2009312042** [comment]
thank you for your quick reply ,i will try it

**Comment by whiteshirt0429** [comment]
we have fixed this bug, and you can try to pull main branch code again.

**Comment by l2009312042** [comment]
in u2 paper  the freq mask is set to 50,but in the conformer.yaml  it is 10  , which  value  shoud be use, and the diff in 
 that value  is big in result ?

the paper say as follows:
SpecAugment[23] is applied with 2 frequency masks with max-
imum frequency mask (F = 50), and 2 time masks with maxi-
mum time mask(T = 50).

**Comment by whiteshirt0429** [comment]
Thank you for your feedback, it was a lerical error of the paper. We actually used frequency mask (F = 10)in our experiments, and we will correct it later
