### ISSUE TITLE
red hat X86_64位系统是否支持，cmake时报错不支持32位相关的组件

### ISSUE THREAD

**Issue by Muzzypepper** [mobvoi/wenet#342]
![image](https://user-images.githubusercontent.com/40849978/116176773-4ceb4080-a745-11eb-87d8-aee082740f3e.png)

**Comment by Muzzypepper** [comment]
libc已安装

**Comment by joewale** [comment]
change the build command below.
mkdir build && cd build && cmake -DINTTYPES_FORMAT:STRING=C99 .. && cmake --build .
