### ISSUE TITLE
Some questions about decode

### ISSUE THREAD

**Issue by yjiangling** [mobvoi/wenet#344]
1. For streaming decode, when we use **rescore decode method**, we use the encoder output + CTC to get the decode result of the current chunk, and then we use decoder to rescore the CTC decode result, Right? 

2. But however, the rescore result is based on the CTC decode result, it can give limitted Promotion (Some wrong tokens are rescored to right tokens based on the right tokens before, but some right tokens might be rescored to wrong tokens based on the wrong tokens before. What's more, if there are some miseed or extra tokens in CTC decode result, rescore decode method can never fix it).

3. When we use **autogressive decode method** to decode can get a much better result, but the question is how to predict the decode numbers during the middle chunks (for only the last chunk has finish token)? Or we can only get CTC decode result during the middle chunks, and re-decode with the autogressive decode method after the last chunk finish decode?

**Comment by robin1001** [comment]
please refer to our papers for the details of how wenet works.
https://mobvoi.github.io/wenet/papers.html

**Comment by yjiangling** [comment]
> please refer to our papers for the details of how wenet works.
> https://mobvoi.github.io/wenet/papers.html

The paper saied like this **attention: apply standard autoregressive beam search on
the AED part of the model.** , in fact, it does not describe clearly, standard autogressive decode method is used on Non-Streaming ASR model is ok, but how to work on Streaming model?

**Comment by yjiangling** [comment]
3.1.2. Decoding
For Python decoding in the research stage, to compare and evaluate different parts of the joint CTC/AED model, WeNet supports
four decoding modes as follows:
1. attention: apply standard autoregressive beam search on the AED part of the model.
2. ctc greedy search: apply CTC greedy search on the CTC part of the model, CTC greedy search is super faster than other modes.
3. ctc prefix beam search: apply CTC prefix beam search on the CTC part of the model, which can give the n-best candidates.
4. attention rescoring: first apply CTC prefix beam search on the CTC part of the model to generate n-best candidates, and then rescore the n-best candidates on the AED decoder part with corresponding encoder output.
**For decoding in the runtime stage, the only attention rescoring is supported since it’s our ultimate solution for production.**

I see, only attention rescoring decode method can be used in Streaming model, the first decode method——attention can only be used in non-streaming model.
