### ISSUE TITLE
bintray boost libraries no longer accessible

### ISSUE THREAD

**Issue by AdolfVonKleist** [mobvoi/wenet#357]
**Describe the bug**
The CMake config specifies bintray as the download location for the boost libs:
 - https://github.com/mobvoi/wenet/blob/80c6936075b42c118ef1742298e3977d59451f1f/runtime/server/x86/CMakeLists.txt#L47
 
as of May 1st this service is no longer available:
 - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

the binaries are available directly from boost:
 - https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz

the CMake spec should be updated to resolve this (I tested the boostorg link and it works).

**Comment by robin1001** [comment]
Thanks for your reminder. we will fix it.

**Comment by robin1001** [comment]
fixed, thanks.
