### ISSUE TITLE
win10识别结果为空，linux识别结果正常

### ISSUE THREAD

**Issue by ZengHorace** [mobvoi/wenet#380]
只是换了平台，其他未做任何改动，这是哪里出了问题啊

**Comment by pengzhendong** [comment]
哥们，你这提问题的方式有待改进，别人根本不知道你这是啥意思。
首先你指的是 python 还是 runtime，你都进行了什么样的操作？
我们的 issues 应该是有模板的，你可以根据模板描述一下你的问题。

**Comment by ZengHorace** [comment]
是python，直接跑的recognize.py，其他未作改动

**Comment by pengzhendong** [comment]
那很有可能是环境的问题，比如 python 版本等等
这个问题好定位，你就在 recognize.py 里面输出一些中间的变量就行，然后跟 linux 的比较一下

**Comment by ZengHorace** [comment]
好的，谢谢
