### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by chenht2010** [mobvoi/wenet#70]
Thank you for this great work.
I trained aishell  follow aishell/s0, and get final.zip
I want try the x86 runtime, but get error:
cmd is :
`./build/decoder_main --chunk_size -1     --wav_path /root/A2_0.wav      --model_path ./final.zip     --dict_path ./words.txt`

the error is:
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/nn/functional.py", line 38, in forward_encoder_chunk
    ret = ret2
  else:
    output = torch.matmul(input, torch.t(weight))
             ~~~~~~~~~~~~ <--- HERE
    if torch.__isnot__(bias, None):
      bias1 = unchecked_cast(Tensor, bias)

Traceback of TorchScript, original code (most recent call last):
  File "/data/Softwares/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/functional.py", line 1676, in forward_encoder_chunk
        ret = torch.addmm(bias, input, weight.t())
    else:
        output = input.matmul(weight.t())
                 ~~~~~~~~~~~~ <--- HERE
        if bias is not None:
            output += bias
RuntimeError: size mismatch, m1: [244 x 4864], m2: [5120 x 256] at ../aten/src/TH/generic/THTensorMath.cpp:41

Did I make some mistakes? Or I need change configuration?
Thank you

**Comment by robin1001** [comment]
![WechatIMG263](https://user-images.githubusercontent.com/6036624/104982023-b7089100-5a44-11eb-9e48-732c7d048995.jpeg)

please scan the QR code and let's talk in wechat group, it's better for quick discuss and response.

**Comment by robin1001** [comment]
It seems that you use our old recipe for training model, the feature of which is 80 fbank + 3 pitch. However, Our runtime only supports fbank feature.

Now the default aishell/s0 uses torchaudio and only fbank feature, you can retrain your model by the latest recipe then it should work for runtime.

**Comment by chenht2010** [comment]
Yes, I try with latest code, error is gone. Thank you.
