### ISSUE TITLE
windows runtime

### ISSUE THREAD

**Issue by hm-0714** [mobvoi/wenet#87]
hi ，i  complied the runtime/x86 code on windows platform，using vs2017 ，but  when run  the  decode_main demo , it  gets  empty recognize result , why ?

**Comment by robin1001** [comment]
We haven't tested in on windows, please test it on your Linux first, if it works then test it on windows. And I wonder your windows means totally windows or "windows with Linux subsystem".

**Comment by hm-0714** [comment]
thank you for your reply!   i run the demo totally windows.

**Comment by robin1001** [comment]
One things should be noticed in pure windows, the LibTorch in CMakeLists.txt should be changed to corresponding windows version https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.6.0%2Bcpu.zip.

Let me know if you make it works on windows, and your bug fix patch is welcomed.

**Comment by hm-0714** [comment]
yes， i had downloaded  windows libtorch  lib. But i  use  vs2017 to compile the code , and i've removed some of the auxiliary code.   
I find the  bug of  "empty result "  to be   caused by two things , one  is  the  train code( i had commented  in Wechat)  ,the other is the  folllowing code: 
FILE* fp = fopen(filename.c_str(), "r");    in  wav.h 

on windows, when  fopen use  'r'  , it  will  ues "rt" to open a file  by default,  this can lead to inconclusive errors when fread the file.  so  it can be change as  folllows:
FILE* fp = fopen(filename.c_str(), "rb");

**Comment by pengzhendong** [comment]
> yes， i had downloaded windows libtorch lib. But i use vs2017 to compile the code , and i've removed some of the auxiliary code.
> I find the bug of "empty result " to be caused by two things , one is the train code( i had commented in Wechat) ,the other is the folllowing code:
> FILE* fp = fopen(filename.c_str(), "r"); in wav.h
> 
> on windows, when fopen use 'r' , it will ues "rt" to open a file by default, this can lead to inconclusive errors when fread the file. so it can be change as folllows:
> FILE* fp = fopen(filename.c_str(), "rb");

Thanks, we fixed it #168.
