### ISSUE TITLE
Issue about encoder-decoder attention

### ISSUE THREAD

**Issue by cosmo1995** [mobvoi/wenet#88]
The encoder outputs are fed into decoder entirely, so the encoder-decoder attention attends to the whole sequence. Right? Why not use monotonic attention?

**Comment by robin1001** [comment]
Yes, it's a standard encoder decoder architecture, the encoder-decoder attention attends to the whole sequence. 
Typically, monotonic attention is used for streaming E2E. However, we use a joint CTC/AED(attention encoder decoder) model in WeNet for streaming , CTC part is for streaming,  AED is for rescoring,  which is more simple and has better accuracy than monotonic attention, so monotonic attention is not adopted in WeNet.
